# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

# prom/blackbox-exporter:v0.25.0

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M


x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Blackbox prober exporter
  # https://github.com/prometheus/blackbox_exporter
  # ====================================================

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    networks:
      public:
      prometheus_gwnetwork:
        aliases:
          - blackbox-exporter.local
    hostname: replica-{{.Task.Slot}}.blackbox-exporter.local
    configs:
      - source: prometheus-blackbox-exporter
    logging: *x-default-logging
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "blackbox-exporter"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1

configs:
  prometheus-blackbox-exporter:
    name: prometheus-blackbox-exporter-v1
    file: ./prometheus/blackbox-exporter.yml
    labels:
      - "io.prometheus.scrape_config=true"

networks:
  public: # The 3rd-party ingress network
    name: public
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
