# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Blackbox exporter
# https://github.com/prometheus/blackbox_exporter
#
scrape_configs:
  - job_name: 'blackbox_exporter'
    dns_sd_configs:
      - names:
          - tasks.blackbox-exporter.internal
        type: A
        port: 9115
        refresh_interval: "30s"
    honor_labels: true
