version: "3.12"
services:
  grafana:
    configs:
    - source: gf-server-entrypoint
      target: /docker-entrypoint-shim.sh
      mode: 365
    deploy:
      replicas: 1
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: grafana
        io.prometheus.scrape_port: "3000"
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
      placement:
        constraints:
        - node.role == manager
        max_replicas_per_node: 1
    entrypoint:
    - /docker-entrypoint-shim.sh
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
    hostname: replica-{{.Task.Slot}}.grafana.local
    image: grafana/grafana:10.0.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana:
        aliases:
        - grafana.local
      prometheus: null
      prometheus_gwnetwork: null
      public:
        aliases:
        - grafana.svc.cluster.local
    ports:
    - target: 3000
      published: 3000
    volumes:
    - type: volume
      source: grafana-data
      target: /var/lib/grafana
    - type: volume
      source: grafana-logs
      target: /var/log/grafana
    - type: volume
      source: grafana-dashboards
      target: /etc/grafana/dashboards
    - type: volume
      source: grafana-provisioning-dashboards
      target: /etc/grafana/provisioning/dashboards
    - type: volume
      source: grafana-provisioning-datasources
      target: /etc/grafana/provisioning/datasources
  grafana-dashboard-provider:
    command:
    - --output-ext=json
    - --output-dir=/grafana-dashboards.d
    - --prometheus-scrape-config-label=io.grafana.dashboard
    configs:
    - source: gf-dashboard-grafana-metrics
    - source: gf-dashboard-prometheus-stats
    - source: gf-dashboard-prometheus-stats-v2
    - source: gf-dashboard-dockerswarm-nodes-dashboard
    - source: gf-dashboard-dockerswarm-services-endpoints
    - source: gf-dashboard-dockerswarm-services
    - source: gf-dashboard-cadvisor
    - source: gf-dashboard-node-exporter
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      resources:
        limits:
          memory: "67108864"
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
        window: 10s
      placement:
        constraints:
        - node.labels.services.promstack_grafana == true
        max_replicas_per_node: 1
    image: swarmlibs/prometheus-config-provider:0.1.0-rc.1
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    volumes:
    - type: volume
      source: grafana-dashboards
      target: /grafana-dashboards.d
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
  grafana-provisioning-config-reloader:
    depends_on:
    - grafana
    - grafana-dashboard-provider
    - grafana-provisioning-dashboard-provider
    - grafana-provisioning-datasource-provider
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      resources:
        limits:
          memory: "67108864"
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
        window: 10s
      placement:
        constraints:
        - node.labels.services.promstack_grafana == true
        max_replicas_per_node: 1
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_SERVER_DOMAIN: replica-{{.Task.Slot}}.grafana.local
    image: swarmlibs/grafana-provisioning-config-reloader:0.1.0-rc.1
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana: null
    volumes:
    - type: volume
      source: grafana-provisioning-config-reloader
      target: /data
    - type: volume
      source: grafana-provisioning-dashboards
      target: /etc/grafana/provisioning/dashboards
    - type: volume
      source: grafana-provisioning-datasources
      target: /etc/grafana/provisioning/datasources
      read_only: true
  grafana-provisioning-dashboard-provider:
    command:
    - --output-dir=/grafana-provisioning-dashboards.d
    - --prometheus-scrape-config-label=io.grafana.provisioning.dashboard
    configs:
    - source: gf-provisioning-dashboards
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      resources:
        limits:
          memory: "67108864"
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
        window: 10s
      placement:
        constraints:
        - node.labels.services.promstack_grafana == true
        max_replicas_per_node: 1
    image: swarmlibs/prometheus-config-provider:0.1.0-rc.1
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    volumes:
    - type: volume
      source: grafana-provisioning-dashboards
      target: /grafana-provisioning-dashboards.d
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
  grafana-provisioning-datasource-provider:
    command:
    - --output-dir=/grafana-provisioning-datasources.d
    - --prometheus-scrape-config-label=io.grafana.provisioning.datasource
    configs:
    - source: gf-provisioning-datasource-prometheus
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      resources:
        limits:
          memory: "67108864"
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
        window: 10s
      placement:
        constraints:
        - node.labels.services.promstack_grafana == true
        max_replicas_per_node: 1
    image: swarmlibs/prometheus-config-provider:0.1.0-rc.1
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    volumes:
    - type: volume
      source: grafana-provisioning-datasources
      target: /grafana-provisioning-datasources.d
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
networks:
  grafana: {}
  prometheus:
    name: prometheus
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
  public:
    name: public
    external: true
volumes:
  grafana-dashboards: {}
  grafana-data: {}
  grafana-logs: {}
  grafana-provisioning-config-reloader: {}
  grafana-provisioning-dashboards: {}
  grafana-provisioning-datasources: {}
configs:
  gf-dashboard-cadvisor:
    name: gf-dashboard-cadvisor-v1
    file: ./grafana/dashboards/cadvisor.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-dockerswarm-nodes-dashboard:
    name: gf-dashboard-dockerswarm-nodes-dashboard-v1
    file: ./grafana/dashboards/dockerswarm-nodes.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-dockerswarm-services:
    name: gf-dashboard-dockerswarm-services-v1
    file: ./grafana/dashboards/dockerswarm-services.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-dockerswarm-services-endpoints:
    name: gf-dashboard-dockerswarm-services-endpoints-v1
    file: ./grafana/dashboards/dockerswarm-services-endpoints.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-grafana-metrics:
    name: gf-dashboard-grafana-metrics-v1
    file: ./grafana/dashboards/grafana-metrics.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-node-exporter:
    name: gf-dashboard-node-exporter-v1
    file: ./grafana/dashboards/node-exporter.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-prometheus-stats:
    name: gf-dashboard-prometheus-stats-v1
    file: ./grafana/dashboards/prometheus-stats.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-prometheus-stats-v2:
    name: gf-dashboard-prometheus-stats-v2
    file: ./grafana/dashboards/prometheus-2-0-stats.json
    labels:
      io.grafana.dashboard: "true"
  gf-provisioning-dashboards:
    name: gf-provisioning-dashboards-v1
    file: ./grafana/provisioning/dashboards/grafana-dashboards.yml
    labels:
      io.grafana.provisioning.dashboard: "true"
  gf-provisioning-datasource-prometheus:
    name: gf-provisioning-datasource-prometheus-v1
    file: ./grafana/provisioning/datasources/prometheus.yaml
    labels:
      io.grafana.provisioning.datasource: "true"
  gf-server-entrypoint:
    name: gf-server-entrypoint-v1
    file: ./grafana/docker-entrypoint-shim.sh
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-deploy:
  placement:
    constraints:
    - node.role == manager
    max_replicas_per_node: 1
  replicas: 1
x-grafana-helpers-deploy:
  placement:
    constraints:
    - node.labels.services.promstack_grafana == true
    max_replicas_per_node: 1
  replicas: 1
x-grafana-helpers-resources-constraints:
  limits:
    memory: 64M
